import { createGlobalStyle } from "styled-components";
import {
  baloobhaina2_bold_woff,
  baloobhaina2_bold_woff2,
  baloobhaina2_regular_woff,
  baloobhaina2_regular_woff2,
  baloobhaina2_semibold_woff,
  baloobhaina2_semibold_woff2,
  iconfont_woff,
  iconfont_woff2,
} from "./fonts";
export const GlobalStyles = createGlobalStyle`
/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on August 22, 2020 */
@font-face {
    font-family: 'baloo_bhaina_2bold';
    src: url('${baloobhaina2_bold_woff2}') format('woff2'),
         url('${baloobhaina2_bold_woff}') format('woff');
    font-weight: normal;
    font-style: normal;

}
@font-face {
    font-family: 'baloo_bhaina_2semibold';
    src: url('${baloobhaina2_semibold_woff2}') format('woff2'),
         url('${baloobhaina2_semibold_woff}') format('woff');
    font-weight: normal;
    font-style: normal;

}
@font-face {
    font-family: 'baloo_bhaina_2regular';
    src: url('${baloobhaina2_regular_woff2}') format('woff2'),
         url('${baloobhaina2_regular_woff}') format('woff');
    font-weight: normal;
    font-style: normal;

}

/*! 
* @package IcoFont 
* @version 1.0.1 
* @author IcoFont https://icofont.com 
* @copyright Copyright (c) 2015 - 2020 IcoFont 
* @license - https://icofont.com/license/
*/
@font-face {
  font-family: IcoFont;
  font-weight: 400;
  font-style: Regular;
  src: url(${iconfont_woff2}) format("woff2"),
    url(${iconfont_woff}) format("woff");
}
[class*=" icofont-"],
[class^="icofont-"] {
  font-family: IcoFont !important;
  speak: none;
  font-style: normal;
  font-weight: 400;
  font-variant: normal;
  text-transform: none;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  line-height: 1;
  -webkit-font-feature-settings: "liga";
  -webkit-font-smoothing: antialiased;
}
.icofont-sun-alt:before {
  content: "\\ee7e";
}
.icofont-moon:before {
  content: "\\ef9e";
}
.icofont-ui-home:before {
  content: "\\ec5e";
}

*{
    font-family: 'baloo_bhaina_2regular';
    box-sizing: border-box;
    margin:0;
    padding:0;
}
#root{
    height: 100vh;
    width: 100vw;
}
a{
    text-decoration: none;
    color: inherit;
}
`;
