import { createGlobalStyle } from "styled-components";
import {
  baloobhaina2_bold_woff,
  baloobhaina2_bold_woff2,
  baloobhaina2_regular_woff,
  baloobhaina2_regular_woff2,
  baloobhaina2_semibold_woff,
  baloobhaina2_semibold_woff2,
} from "./fonts";
export const GlobalStyles = createGlobalStyle`
/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on August 22, 2020 */
@font-face {
    font-family: 'baloo_bhaina_2bold';
    src: url('${baloobhaina2_bold_woff2}') format('woff2'),
         url('${baloobhaina2_bold_woff}') format('woff');
    font-weight: normal;
    font-style: normal;

}
@font-face {
    font-family: 'baloo_bhaina_2semibold';
    src: url('${baloobhaina2_semibold_woff2}') format('woff2'),
         url('${baloobhaina2_semibold_woff}') format('woff');
    font-weight: normal;
    font-style: normal;

}
@font-face {
    font-family: 'baloo_bhaina_2regular';
    src: url('${baloobhaina2_regular_woff2}') format('woff2'),
         url('${baloobhaina2_regular_woff}') format('woff');
    font-weight: normal;
    font-style: normal;

}

*{
    font-family: 'baloo_bhaina_2regular';
    box-sizing: border-box;
    margin:0;
    padding:0;
}
#root{
    height: 100vh;
    width: 100vw;
}
a{
    text-decoration: none;
    color: inherit;
}
`;
